encyclopedia/urls.py
from django.urls import path

from . import views

app_name="wiki"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.wiki, name="wiki"),
    path("add", views.add, name="add"),
    path("random", views.random, name="random"),
    path("edit/<str:title>", views.edit, name="edit"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from . import util
from django import forms
from markdown2 import Markdown
from random import choice

markdowner = Markdown()

# Define search form class
class NewSearchForm(forms.Form):
    q = forms.CharField(min_length=1, max_length=255)

# Define new page form class
class NewAddForm(forms.Form):
    title = forms.CharField(min_length=1, max_length=255)
    content = forms.CharField(widget=forms.Textarea)

# Define new edit form class
class NewEditForm(forms.Form):
    eContent = forms.CharField(widget=forms.Textarea)


# Define index route
def index(request):

    # if method is post
    if request.method == "POST":

        form = NewSearchForm(request.POST)
        # if form is valid
        if form.is_valid():

            q = form.cleaned_data["q"]

            # if user query is not a page
            if (util.get_entry(q) is None):
               
               search = []

               for entry in util.list_entries():
                    entrylower = entry.lower()

                    # search for substring in user query
                    if q in entrylower:
                        search.append(entry)

                # pass the searched result to search.html
               return render(request, "encyclopedia/search.html", {
                "search": search,
                "q": q
               })

            # if user query is a page
            else:

                # return entry page of requested query 
                return render(request, "encyclopedia/entry.html", {
                "title": q,
                "entry": markdowner.convert(util.get_entry(q))
                })

    # if method is get
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form": NewSearchForm()
    })
    
# define the wiki route
def wiki(request, title):

    # if requested entry is none
    if (util.get_entry(title) is None):
        # render error.html
        return render(request, "encyclopedia/error.html", {
            "title": "Error | 404",
            "message": "404 | No such entry found"
        })
    # if requested entry exists
    else:
        # render entry.html
        return render(request, "encyclopedia/entry.html", {
            "title": title,
            "entry": markdowner.convert(util.get_entry(title))
        })

# define the add route
def add(request):

    # if request method is post
    if request.method == "POST":
        form = NewAddForm(request.POST)

        # validate form
        if form.is_valid():

            # get title from form
            title = form.cleaned_data["title"]

            # if title does not exist
            if (util.get_entry(title) is None):

                # get the content from form
                content = form.cleaned_data["content"]

                # save the entry using util.py
                util.save_entry(title, content)

                # also, render that entry.html
                return render(request, "encyclopedia/entry.html", {
                    "title": title,
                    "entry": markdowner.convert(util.get_entry(title))
                })
            
            # if the title already exists
            else:
                # render error.html with message
                return render(request, "encyclopedia/error.html", {
                    "title":"Error",
                    "message": "Sorry, page already exits."
                })


    # if request method is get, render add.html to add new page
    return render(request, 'encyclopedia/add.html', {
        'aForm': NewAddForm()
    })

# define random route
def random(request):
    
    # return random page with entry.html
    return render(request, "encyclopedia/entry.html", {
                    "title": choice(util.list_entries()),
                    "entry": markdowner.convert(util.get_entry(choice(util.list_entries())))
    })

def edit(request, title):


    if request.method == "POST":

        form = NewEditForm(request.POST)
        if form.is_valid():

            newContent = form.cleaned_data["eContent"]

            util.save_entry(title,newContent)
            return render(request, "encyclopedia/entry.html", {
                    "title": title,
                    "entry": markdowner.convert(util.get_entry(title))
                })


    initial = util.get_entry(title)
    eform = NewEditForm(initial={"eContent": initial})

    return render(request, "encyclopedia/edit.html", {
        "eform": eform,
        "title": title,
        "initial": initial
    })


    


    

    

encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create a new page
{% endblock %}

{% block body %}
<h1>Create New Page</h1>
    <form method="post" action="{% url 'wiki:add' %}">
        {% csrf_token %}
        {{aForm}}
        <input type='submit' value="Create">

    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit {{ title }}
{% endblock %}

{% block body %}
<h1>{{title}}</h1>
    <form method="post" action="../edit/{{ title }}">
       {% csrf_token %}
       {{ eform }}
    <input type='submit' value="Edit">

    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
     {{entry|safe}}

     <a href="../edit/{{ title }}">Edit</a>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
    {{message}}
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="wiki/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:index' %}" method="post">
                    {% csrf_token %}
                    {{form}}
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:add'%}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random'%}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search
{% endblock %}

{% block body %}
    <h1>Your Search Results</h1>

    <ul>
        {% for result in search %}
            <li><a href="wiki/{{ result }}">{{ result }}</a></li>
        {% empty%}
            <li>No such entry found with word {{q}}.</li>
        {% endfor %}
    </ul>

{% endblock %}